server:
 port: 41801
    # 统一接口访问前缀
 servlet-path: /monitor-client


spring:
    profiles:
        active: dev
    datasource:
        name: ReadAndWrite
        url: jdbc:mysql://101.200.170.15:30002/us_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 80
        initialSize: 2
        maxIdle: 4
        maxWait: 30000
        minIdle: 2
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

management:
    address: 127.0.0.1
mybatis:
    my:
        beanPath: com.us.order.dao.beans
        mapperXmlPath: classpath:mapper/*.xml
        mapperPath: com.us.order.dao.mapper

